pipeline{
    agent any
    tools{
        maven 'Maven'
    }
    stages{
        stage("build maven"){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main'], [name: '*/feature.*']], extensions: [], userRemoteConfigs: [[credentialsId: 'github_credentials', url: 'https://github.com/Arjuna1112/Spring_Boot.git']]])
                sh "mvn -Dmaven.test.failure.ignore=true clean package"
            }
        }
        stage("test"){
            steps{
                echo 'testing the application'
            }
        }
        stage("deploy"){
            steps{
                echo 'deploying the application'
            }
        }
    }
}